package tic.tac.toe;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.System.Logger;
import java.util.logging.Level;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ging3r
 */
public class Comments extends javax.swing.JFrame {

    /**
     * Creates new form Comments
     */
    public Comments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommentsTable = new javax.swing.JTable();
        Import = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        MENU = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        How = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();
        PLAY = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Settings = new javax.swing.JMenuItem();
        AboutUs = new javax.swing.JMenu();
        Rate = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Krungthep", 2, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("COMMENTS!");
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 50));

        CommentsTable.setBackground(new java.awt.Color(220, 233, 255));
        CommentsTable.setFont(new java.awt.Font("Krungthep", 2, 18)); // NOI18N
        CommentsTable.setForeground(new java.awt.Color(153, 153, 255));
        CommentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#NUMBER", "PLAYERS COMMENTS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CommentsTable.setSelectionForeground(new java.awt.Color(127, 127, 193));
        jScrollPane1.setViewportView(CommentsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 400, 170));

        Import.setBackground(new java.awt.Color(55, 6, 128));
        Import.setFont(new java.awt.Font("Krungthep", 2, 24)); // NOI18N
        Import.setForeground(new java.awt.Color(255, 255, 255));
        Import.setText("IMPORT");
        Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportActionPerformed(evt);
            }
        });
        jPanel1.add(Import, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 670, 140, 50));

        update1.setBackground(new java.awt.Color(55, 6, 128));
        update1.setFont(new java.awt.Font("Krungthep", 2, 24)); // NOI18N
        update1.setForeground(new java.awt.Color(255, 255, 255));
        update1.setText("UPDATE");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel1.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 670, 140, 50));

        Add.setBackground(new java.awt.Color(55, 6, 128));
        Add.setFont(new java.awt.Font("Krungthep", 2, 24)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 140, 50));

        MENU.setBackground(new java.awt.Color(55, 6, 128));
        MENU.setFont(new java.awt.Font("Krungthep", 2, 24)); // NOI18N
        MENU.setForeground(new java.awt.Color(255, 255, 255));
        MENU.setText("MENU");
        MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENUActionPerformed(evt);
            }
        });
        jPanel1.add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 140, 50));

        EXIT.setBackground(new java.awt.Color(55, 6, 128));
        EXIT.setFont(new java.awt.Font("Krungthep", 2, 24)); // NOI18N
        EXIT.setForeground(new java.awt.Color(255, 255, 255));
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 160, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tumblr.gif"))); // NOI18N
        jLabel5.setText("jLabel3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 1030, 760));

        Menu.setForeground(new java.awt.Color(121, 48, 128));
        Menu.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N

        How.setBackground(new java.awt.Color(127, 127, 193));
        How.setForeground(new java.awt.Color(255, 255, 255));
        How.setText("File");
        How.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(181, 144, 181));
        jMenuItem1.setText("MENU!");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        How.add(jMenuItem1);

        About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        About.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N
        About.setForeground(new java.awt.Color(181, 144, 181));
        About.setText("ABOUT CREATOR!");
        About.setToolTipText("");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        How.add(About);

        PLAY.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        PLAY.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N
        PLAY.setForeground(new java.awt.Color(181, 144, 181));
        PLAY.setText("HOW TO PLAY?");
        PLAY.setToolTipText("");
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        How.add(PLAY);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        How.add(jSeparator1);

        Settings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Settings.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N
        Settings.setForeground(new java.awt.Color(181, 144, 181));
        Settings.setText("SETTINGS!");
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });
        How.add(Settings);

        Menu.add(How);

        AboutUs.setBackground(new java.awt.Color(177, 141, 177));
        AboutUs.setForeground(new java.awt.Color(255, 255, 255));
        AboutUs.setText("About Us");
        AboutUs.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });

        Rate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Rate.setFont(new java.awt.Font("Krungthep", 2, 14)); // NOI18N
        Rate.setForeground(new java.awt.Color(181, 144, 181));
        Rate.setText("RATE!");
        Rate.setToolTipText("");
        Rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateActionPerformed(evt);
            }
        });
        AboutUs.add(Rate);

        Menu.add(AboutUs);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");

        if (JOptionPane.showConfirmDialog(frame, "CONFIRM IF YOU WANT TO EXIT ",
                "TIC TAC TOE", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_EXITActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MENU m = new MENU();

        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "HI! MY NAME IS JANA MALIBARI AND I'M THE CREATOR OF THIS GAME\n THIS IS THE FIRST GAME I HAVE EVER MADE AND I HOPE IT SUITS U PLAYER <3 ",
                "ABOUT CREATOR", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AboutActionPerformed

    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "TO WIN THE GAME, YOU HAVE TO GET 3 'X'S STRIGHT OR 3 '0'S!",
                "HOW TO PLAY?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_PLAYActionPerformed

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
        //CHANGE COLOR
    }//GEN-LAST:event_SettingsActionPerformed

    private void RateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateActionPerformed
        // TODO add your handling code here:
        Comments r = new Comments();

        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_RateActionPerformed

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutUsActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        try {

            String filepath = "//Users/ging3r/NetBeansProjects/TIC-TAC-TOE./src/comments.csv";

            DefaultTableModel model = (DefaultTableModel) CommentsTable.getModel();

            String num = JOptionPane.showInputDialog("ENTER # NUMBER OF COMMENT!");
            int Num = Integer.parseInt(num);

            String Comment = JOptionPane.showInputDialog("ENTER YOUR COMMENT!");

            Object rowData[] = new Object[2];
            rowData[0] = Num;
            rowData[1] = Comment;

            model.addRow(rowData);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "PLEASE ENTER NUMBERS ONLY ON THE#NUM SECTION!");

        }

        /**
         * BufferedReader reader = null; String line = ""; try{
         *
         * reader = new BufferedReader(new FileReader(file)); while((line =
         * reader.readLine()) != null){
         *
         * String [] row = line.split(",");
         *
         * for (String index : row){ System.out.printf("%-10s", index); } }
         * }catch(Exception e){
         *
         * e.printStackTrace();
         *
         * }finally{ try { reader.close(); } catch (IOException ex) {
         * Logger.getLogger(RATE.class.getName()).log(Level.SEVERE, null, ex); }
         * }
         *
         *
         *
         *
         * try {
         *
         * Num = Integer.parseInt(num.getText());
         * if(num.getText().equals("")||CommentText.getText().equals("")){
         *
         * JOptionPane.showMessageDialog(this, "PLEASE ENTER IN ALL THE
         * BOXES!"); }else {
         *
         * String dataRow[] ={num.getText(), CommentText.getText()};
         *
         * DefaultTableModel model = (DefaultTableModel)
         * CommentsTable.getModel(); model.addRow(dataRow);
         *
         * JOptionPane.showMessageDialog(this, "YOUR COMMENT WERE ADD
         * SECCESSFULLY!");
         *
         * num.setText(""); CommentText.setText("");
         *
         * }
         *
         * } catch (NumberFormatException e) {
         *
         * JOptionPane.showMessageDialog(null, "PLEASE ENTER NUMBERS ONLY ON THE
         * #NUM SECTION!"); num.equals(""); CommentText.equals("");
         *
         * }
         *
         *
         *
         *
         * try {
         *
         * Num = Integer.parseInt(num.getText());
         *
         * } catch (NumberFormatException e) {
         *
         * JOptionPane.showMessageDialog(null, "PLEASE ENTER NUMBERS ONLY ON THE
         * #NUM SECTION!");
         *
         * }
         *
         * Comments.AddCommentToRow(new Object[]{ num.getText(),
         * CommentText.getText(),});*
         */

    }//GEN-LAST:event_AddActionPerformed

    private void MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENUActionPerformed
        // TODO add your handling code here:

        MENU m = new MENU();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_MENUActionPerformed

    private void ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportActionPerformed
        String filepath = "/Users/ging3r/NetBeansProjects/TIC-TAC-TOE./src/comments.csv";
        File file = new File(filepath);
        String num = JOptionPane.showInputDialog("ENTER # NUMBER OF COMMENT!");
        try {

            BufferedReader buff = new BufferedReader(new FileReader(file));
            String firstLine = buff.readLine().trim();
            String[] columnsNames = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel) CommentsTable.getModel();
            model.setColumnIdentifiers(columnsNames);
            
            
            Object [] tableLines = buff.lines().toArray();
            
            for(int i = 0; i<tableLines.length; i++){
                
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(Level.SEVERE, null, ex);
        }

         }//GEN-LAST:event_ImportActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) CommentsTable.getModel();
        int selectedRowIndex = CommentsTable.getSelectedRow();

        try {
            String num = model.getValueAt(selectedRowIndex, 0).toString();
            String Comment = model.getValueAt(selectedRowIndex, 1).toString();

            String newNum = JOptionPane.showInputDialog(null, "THE #NUMBER", num);
            String newCom = JOptionPane.showInputDialog(null, "THE Comment", Comment);

            model.setValueAt(newNum, selectedRowIndex, 0);
            model.setValueAt(newCom, selectedRowIndex, 1);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "NO ROW WAS SELECTED " + e);
        }
    }//GEN-LAST:event_update1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenu AboutUs;
    private javax.swing.JButton Add;
    public static javax.swing.JTable CommentsTable;
    private javax.swing.JButton EXIT;
    private javax.swing.JMenu How;
    private javax.swing.JButton Import;
    private javax.swing.JButton MENU;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem PLAY;
    private javax.swing.JMenuItem Rate;
    private javax.swing.JMenuItem Settings;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
